"""Initial migration and CribbageGame table

Revision ID: 701d5707cef3
Revises: 
Create Date: 2025-07-02 12:35:18.691754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701d5707cef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cribbage_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opponent_user_id', sa.Integer(), nullable=True),
    sa.Column('guest_opponent_name', sa.String(length=100), nullable=True),
    sa.Column('user_score', sa.Integer(), nullable=False),
    sa.Column('opponent_score', sa.Integer(), nullable=False),
    sa.Column('is_skunk', sa.Boolean(), nullable=False),
    sa.Column('is_double_skunk', sa.Boolean(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opponent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cribbage_games')
    # ### end Alembic commands ###
